=== holmes-ra/yiiStuff/protected/extensions/yapeal/install/xmlschema03.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="schema">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="table" type="table" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="sql" type="sql" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="version" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:decimal">
            <xs:enumeration value="0.1"/>
            <xs:enumeration value="0.2"/>
            <xs:enumeration value="0.3"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="table">
    <xs:sequence>
      <xs:element name="descr" type="xs:string" minOccurs="0" maxOccurs="1"/>
      <xs:choice>
        <xs:element name="DROP">
          <xs:complexType/>
        </xs:element>
        <xs:sequence>
          <xs:element name="field" type="field" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element name="index" type="index" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element name="constraint" minOccurs="0" maxOccurs="unbounded">
            <xs:complexType mixed="true">
              <xs:attribute name="platform" type="xs:string" use="optional"/>
            </xs:complexType>
          </xs:element>
          <xs:element name="opt" minOccurs="0" maxOccurs="unbounded">
            <xs:complexType mixed="true">
              <xs:attribute name="platform" type="xs:string" use="optional"/>
            </xs:complexType>
          </xs:element>
          <xs:element name="data" type="data" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="platform" type="xs:string" use="optional"/>
    <xs:attribute name="version" type="xs:string" use="optional"/>
  </xs:complexType>
  <xs:complexType name="data">
    <xs:sequence>
      <xs:element name="descr" type="xs:string" minOccurs="0" maxOccurs="1"/>
      <xs:element name="row" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="f" minOccurs="1" maxOccurs="unbounded">
              <xs:complexType mixed="true">
                <xs:attribute name="name" type="xs:string" use="optional"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="platform" type="xs:string" use="optional"/>
  </xs:complexType>
  <xs:complexType name="field">
    <xs:sequence>
      <xs:element name="descr" type="xs:string" minOccurs="0" maxOccurs="1"/>
      <xs:choice minOccurs="0" maxOccurs="1">
        <xs:element name="NOTNULL">
          <xs:complexType/>
        </xs:element>
        <xs:element name="KEY">
          <xs:complexType/>
        </xs:element>
        <xs:element name="PRIMARY">
          <xs:complexType/>
        </xs:element>
      </xs:choice>
      <xs:choice minOccurs="0" maxOccurs="1">
        <xs:element name="AUTO">
          <xs:complexType/>
        </xs:element>
        <xs:element name="AUTOINCREMENT">
          <xs:complexType/>
        </xs:element>
      </xs:choice>
      <xs:choice minOccurs="0" maxOccurs="1">
        <xs:element name="DEFAULT">
          <xs:complexType>
            <xs:attribute name="value" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="DEFDATE">
          <xs:complexType/>
        </xs:element>
        <xs:element name="DEFTIMESTAMP">
          <xs:complexType/>
        </xs:element>
      </xs:choice>
      <xs:element name="NOQUOTE" minOccurs="0" maxOccurs="1">
        <xs:complexType/>
      </xs:element>
      <xs:element name="UNSIGNED" minOccurs="0" maxOccurs="1">
        <xs:complexType/>
      </xs:element>
      <xs:element name="constraint" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType mixed="true">
          <xs:attribute name="platform" type="xs:string" use="optional"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="opt" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType mixed="true">
          <xs:attribute name="platform" type="xs:string" use="optional"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attributeGroup ref="fieldAttrs"/>
  </xs:complexType>
  <xs:complexType name="index">
    <xs:sequence>
      <xs:element name="descr" type="xs:string" minOccurs="0" maxOccurs="1"/>
      <xs:choice>
        <xs:element name="DROP">
          <xs:complexType/>
        </xs:element>
        <xs:sequence>
          <xs:element name="col" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType mixed="true">
            </xs:complexType>
          </xs:element>
          <xs:element name="CLUSTERED" minOccurs="0" maxOccurs="1">
            <xs:complexType/>
          </xs:element>
          <xs:element name="BITMAP" minOccurs="0" maxOccurs="1">
            <xs:complexType/>
          </xs:element>
          <xs:element name="UNIQUE" minOccurs="0" maxOccurs="1">
            <xs:complexType/>
          </xs:element>
          <xs:element name="FULLTEXT" minOccurs="0" maxOccurs="1">
            <xs:complexType/>
          </xs:element>
          <xs:element name="HASH" minOccurs="0" maxOccurs="1">
            <xs:complexType/>
          </xs:element>
        </xs:sequence>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="platform" type="xs:string" use="optional"/>
  </xs:complexType>
  <xs:complexType name="sql">
    <xs:sequence>
      <xs:element name="descr" type="xs:string" minOccurs="0" maxOccurs="1"/>
      <xs:element name="query" minOccurs="1" maxOccurs="unbounded">
        <xs:complexType mixed="true">
          <xs:attribute name="platform" type="xs:string" use="optional"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="optional"/>
    <xs:attribute name="platform" type="xs:string" use="optional"/>
    <xs:attribute name="key" type="xs:string" use="optional"/>
    <xs:attribute name="prefixmethod" use="optional">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="AUTO"/>
          <xs:enumeration value="MANUAL"/>
          <xs:enumeration value="NONE"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
  <xs:attributeGroup name="fieldAttrs">
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="B"/>
          <xs:enumeration value="C"/>
          <xs:enumeration value="C2"/>
          <xs:enumeration value="D"/>
          <xs:enumeration value="F"/>
          <xs:enumeration value="I"/>
          <xs:enumeration value="I1"/>
          <xs:enumeration value="I2"/>
          <xs:enumeration value="I4"/>
          <xs:enumeration value="I8"/>
          <xs:enumeration value="L"/>
          <xs:enumeration value="N"/>
          <xs:enumeration value="T"/>
          <xs:enumeration value="TS"/>
          <xs:enumeration value="X"/>
          <xs:enumeration value="X2"/>
          <xs:enumeration value="XL"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="size" type="xs:string" use="optional"/>
    <xs:attribute name="opts" type="xs:string" use="optional"/>
  </xs:attributeGroup>
</xs:schema>

=== holmes-ra/yiiStuff/protected/extensions/yapeal/install/account.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema version="0.3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xmlschema03.xsd">
<!--
/**
 * XML from Yapeal.
 *
 * PHP version 5
 *
 * LICENSE: This file is part of Yet Another Php Eve Api library also know
 * as Yapeal which will be used to refer to it in the rest of this license.
 *
 *  Yapeal is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Yapeal is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with Yapeal. If not, see <http://www.gnu.org/licenses/>.
 *
 * @author     Michael Cummings <mgcummings@yahoo.com>
 * @copyright  Copyright (c) 2008-2012, Michael Cummings
 * @license    http://www.gnu.org/copyleft/lesser.html GNU LGPL
 * @package    Yapeal
 * @subpackage Install
 * @link       http://code.google.com/p/yapeal/
 * @link       http://www.eveonline.com/
 */
-->
  <!-- Account Section -->
  <table name="accountAccountStatus">
    <field name="`keyID`" type="I8" size="20">
      <KEY/>
      <UNSIGNED/>
    </field>
    <field name="`createDate`" type="T">
      <NOTNULL/>
    </field>
    <field name="`logonCount`" type="I8" size="20">
      <NOTNULL/>
      <UNSIGNED/>
    </field>
    <field name="`logonMinutes`" type="I8" size="20">
      <NOTNULL/>
      <UNSIGNED/>
    </field>
    <field name="`paidUntil`" type="T">
      <NOTNULL/>
    </field>
    <opt platform="mysql"> ENGINE = InnoDB COLLATE = utf8_unicode_ci</opt>
  </table>
  <table name="accountAPIKeyInfo">
    <field name="`keyID`" type="I8" size="20">
      <KEY/>
      <UNSIGNED/>
    </field>
    <field name="`accessMask`" type="I8" size="20">
      <NOTNULL/>
      <UNSIGNED/>
    </field>
    <field name="`expires`" type="T">
      <NOTNULL/>
      <DEFAULT value="2038-01-19 03:14:07"/>
    </field>
    <field name="`type`" type="C" size="11">
      <NOTNULL/>
    </field>
    <index name="`accountAPIKeyInfo1`">
      <col>`type`</col>
    </index>
    <opt platform="mysql"> ENGINE = InnoDB COLLATE = utf8_unicode_ci</opt>
  </table>
  <table name="accountCharacters">
    <field name="`characterID`" type="I8" size="20">
      <KEY/>
      <UNSIGNED/>
    </field>
    <field name="`characterName`" type="C" size="255">
      <NOTNULL/>
    </field>
    <field name="`corporationID`" type="I8" size="20">
      <NOTNULL/>
      <UNSIGNED/>
    </field>
    <field name="`corporationName`" type="C" size="255">
      <NOTNULL/>
    </field>
    <index name="`accountCharacters1`">
      <col>`corporationID`</col>
    </index>
    <opt platform="mysql"> ENGINE = InnoDB COLLATE = utf8_unicode_ci</opt>
  </table>
  <table name="accountKeyBridge">
    <field name="`keyID`" type="I8" size="20">
      <KEY/>
      <UNSIGNED/>
    </field>
    <field name="`characterID`" type="I8" size="20">
      <KEY/>
      <UNSIGNED/>
    </field>
    <index name="`accountKeyBridge1`">
      <col>`characterID`</col>
      <col>`keyID`</col>
      <UNIQUE/>
    </index>
    <opt platform="mysql"> ENGINE = InnoDB COLLATE = utf8_unicode_ci</opt>
  </table>
  <sql prefixmethod="MANUAL">
    <query platform="mysql">ALTER TABLE `%%PaccountAPIKeyInfo` MODIFY `type` ENUM('Account','Character','Corporation') COLLATE ascii_general_ci NOT NULL</query>
  </sql>
  <sql prefixmethod="MANUAL">
    <query platform="mysql">INSERT INTO `%%PutilSections` (`activeAPIMask`,`isActive`,`sectionID`,`section`)
      VALUES(33554433,1,1,'account')
      ON DUPLICATE KEY UPDATE `activeAPIMask`=VALUES(`activeAPIMask`),`sectionID`=VALUES(`sectionID`),`section`=VALUES(`section`)
    </query>
  </sql>
</schema>

=== holmes-ra/yiiStuff/protected/extensions/yapeal/install/server.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema version="0.3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xmlschema03.xsd">
<!--
/**
 * XML from Yapeal.
 *
 * PHP version 5
 *
 * LICENSE: This file is part of Yet Another Php Eve Api library also know
 * as Yapeal which will be used to refer to it in the rest of this license.
 *
 *  Yapeal is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Yapeal is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with Yapeal. If not, see <http://www.gnu.org/licenses/>.
 *
 * @author     Michael Cummings <mgcummings@yahoo.com>
 * @copyright  Copyright (c) 2008-2012, Michael Cummings
 * @license    http://www.gnu.org/copyleft/lesser.html GNU LGPL
 * @package    Yapeal
 * @subpackage Install
 * @link       http://code.google.com/p/yapeal/
 * @link       http://www.eveonline.com/
 */
-->
  <!-- Server Section -->
  <table name="serverServerStatus">
    <field name="`onlinePlayers`" type="I8" size="20">
      <NOTNULL/>
      <UNSIGNED/>
    </field>
    <field name="`serverName`" type="C" size="32">
      <KEY/>
    </field>
    <field name="`serverOpen`" type="C" size="32">
      <NOTNULL/>
    </field>
    <opt platform="mysql"> ENGINE = InnoDB COLLATE = utf8_unicode_ci</opt>
  </table>
  <sql prefixmethod="MANUAL">
    <query platform="mysql">INSERT INTO `%%PutilSections` (`activeAPIMask`,`isActive`,`sectionID`,`section`)
      VALUES(1,1,6,'server')
      ON DUPLICATE KEY UPDATE `activeAPIMask`=VALUES(`activeAPIMask`),`sectionID`=VALUES(`sectionID`),`section`=VALUES(`section`)
    </query>
  </sql>
</schema>
